// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLKS.Data.QLKSDbContext;

#nullable disable

namespace QLKS.Migrations
{
    [DbContext(typeof(QLKSDbContext))]
    [Migration("20260328094843_KhoiTao")]
    partial class KhoiTao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.LoaiPhong", b =>
                {
                    b.Property<int>("LoaiPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiPhongId"));

                    b.Property<double>("DienTich")
                        .HasColumnType("float");

                    b.Property<decimal>("GiaCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoaiPhongId");

                    b.ToTable("LoaiPhongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.LoaiPhongThietBi", b =>
                {
                    b.Property<int>("LoaiPhongThietBiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiPhongThietBiId"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiPhongId")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("ThietBiId")
                        .HasColumnType("int");

                    b.HasKey("LoaiPhongThietBiId");

                    b.HasIndex("LoaiPhongId");

                    b.HasIndex("ThietBiId");

                    b.ToTable("LoaiPhongThietBis");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.LoaiPhongTienNghi", b =>
                {
                    b.Property<int>("LoaiPhongTienNghiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiPhongTienNghiId"));

                    b.Property<int>("LoaiPhongId")
                        .HasColumnType("int");

                    b.Property<int>("TienNghiId")
                        .HasColumnType("int");

                    b.HasKey("LoaiPhongTienNghiId");

                    b.HasIndex("LoaiPhongId");

                    b.HasIndex("TienNghiId");

                    b.ToTable("LoaiPhongTienNghis");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.Phong", b =>
                {
                    b.Property<int>("PhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhongId"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiPhongId")
                        .HasColumnType("int");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TangId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiPhong")
                        .HasColumnType("int");

                    b.HasKey("PhongId");

                    b.HasIndex("LoaiPhongId");

                    b.HasIndex("TangId");

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.Tang", b =>
                {
                    b.Property<int>("TangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TangId"));

                    b.Property<int>("SoTang")
                        .HasColumnType("int");

                    b.HasKey("TangId");

                    b.ToTable("Tangs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.ThietBi", b =>
                {
                    b.Property<int>("ThietBiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThietBiId"));

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThietBiId");

                    b.ToTable("ThietBis");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.TienNghi", b =>
                {
                    b.Property<int>("TienNghiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TienNghiId"));

                    b.Property<string>("TenTienNghi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TienNghiId");

                    b.ToTable("TienNghis");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.LoaiPhongThietBi", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_Phong.LoaiPhong", "LoaiPhong")
                        .WithMany("LoaiPhongThietBis")
                        .HasForeignKey("LoaiPhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLKS.Data.Entities.Nhom_Phong.ThietBi", "ThietBi")
                        .WithMany("LoaiPhongThietBis")
                        .HasForeignKey("ThietBiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.LoaiPhongTienNghi", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_Phong.LoaiPhong", "LoaiPhong")
                        .WithMany("LoaiPhongTienNghis")
                        .HasForeignKey("LoaiPhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLKS.Data.Entities.Nhom_Phong.TienNghi", "TienNghi")
                        .WithMany("LoaiPhongTienNghis")
                        .HasForeignKey("TienNghiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");

                    b.Navigation("TienNghi");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.Phong", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_Phong.LoaiPhong", "LoaiPhong")
                        .WithMany("Phongs")
                        .HasForeignKey("LoaiPhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLKS.Data.Entities.Nhom_Phong.Tang", "Tang")
                        .WithMany("Phongs")
                        .HasForeignKey("TangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");

                    b.Navigation("Tang");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.LoaiPhong", b =>
                {
                    b.Navigation("LoaiPhongThietBis");

                    b.Navigation("LoaiPhongTienNghis");

                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.Tang", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.ThietBi", b =>
                {
                    b.Navigation("LoaiPhongThietBis");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.TienNghi", b =>
                {
                    b.Navigation("LoaiPhongTienNghis");
                });
#pragma warning restore 612, 618
        }
    }
}
