// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLKS.Data.QLKSDbContext;

#nullable disable

namespace QLKS.Migrations
{
    [DbContext(typeof(QLKSDbContext))]
    partial class QLKSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.ChiTietDatPhong", b =>
                {
                    b.Property<int>("ChiTietDatPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietDatPhongId"));

                    b.Property<bool>("DaLapHoaDon")
                        .HasColumnType("bit");

                    b.Property<int>("DatPhongId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PhongId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianNhanDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTraDuKien")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ChiTietDatPhongId");

                    b.HasIndex("DatPhongId");

                    b.HasIndex("PhongId");

                    b.ToTable("ChiTietDatPhongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.ChiTietNhanPhong", b =>
                {
                    b.Property<int>("ChiTietNhanPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietNhanPhongId"));

                    b.Property<int>("ChiTietDatPhongId")
                        .HasColumnType("int");

                    b.Property<int>("NhanPhongId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianNhanThucTe")
                        .HasColumnType("datetime2");

                    b.HasKey("ChiTietNhanPhongId");

                    b.HasIndex("ChiTietDatPhongId")
                        .IsUnique();

                    b.HasIndex("NhanPhongId");

                    b.ToTable("ChiTietNhanPhongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.ChiTietTraPhong", b =>
                {
                    b.Property<int>("ChiTietTraPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietTraPhongId"));

                    b.Property<int>("ChiTietNhanPhongId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianTraThucTe")
                        .HasColumnType("datetime2");

                    b.Property<int>("TraPhongId")
                        .HasColumnType("int");

                    b.HasKey("ChiTietTraPhongId");

                    b.HasIndex("ChiTietNhanPhongId")
                        .IsUnique();

                    b.HasIndex("TraPhongId");

                    b.ToTable("ChiTietTraPhongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.DatPhong", b =>
                {
                    b.Property<int>("DatPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatPhongId"));

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<bool>("LaDatTruoc")
                        .HasColumnType("bit");

                    b.Property<string>("MaDatPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienCoc")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("DatPhongId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("MaDatPhong")
                        .IsUnique();

                    b.ToTable("DatPhongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.NhanPhong", b =>
                {
                    b.Property<int>("NhanPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanPhongId"));

                    b.Property<string>("MaNhanPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.HasKey("NhanPhongId");

                    b.HasIndex("MaNhanPhong")
                        .IsUnique();

                    b.HasIndex("NhanVienId");

                    b.ToTable("NhanPhongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.TraPhong", b =>
                {
                    b.Property<int>("TraPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraPhongId"));

                    b.Property<string>("MaTraPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.HasKey("TraPhongId");

                    b.HasIndex("MaTraPhong")
                        .IsUnique();

                    b.HasIndex("NhanVienId");

                    b.ToTable("TraPhongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DichVu.DichVu", b =>
                {
                    b.Property<int>("DichVuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DichVuId"));

                    b.Property<bool>("ConSuDung")
                        .HasColumnType("bit");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DichVuId");

                    b.HasIndex("MaDichVu")
                        .IsUnique();

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DichVu.SuDungDichVu", b =>
                {
                    b.Property<int>("SuDungDichVuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuDungDichVuId"));

                    b.Property<int>("ChiTietDatPhongId")
                        .HasColumnType("int");

                    b.Property<bool>("DaLapHoaDon")
                        .HasColumnType("bit");

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianSuDung")
                        .HasColumnType("datetime2");

                    b.HasKey("SuDungDichVuId");

                    b.HasIndex("ChiTietDatPhongId");

                    b.HasIndex("DichVuId");

                    b.ToTable("SuDungDichVus");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_HoaDon_ThanhToan.ChiTietHoaDon", b =>
                {
                    b.Property<int>("ChiTietHoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietHoaDonId"));

                    b.Property<int?>("ChiTietDatPhongId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("SuDungDichVuId")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ChiTietHoaDonId");

                    b.HasIndex("ChiTietDatPhongId");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("SuDungDichVuId");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_HoaDon_ThanhToan.HoaDon", b =>
                {
                    b.Property<int>("HoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonId"));

                    b.Property<int>("DatPhongId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<decimal>("TongThanhToan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("HoaDonId");

                    b.HasIndex("DatPhongId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_HoaDon_ThanhToan.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhToanId"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhuongThucThanhToan")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianThanhToan")
                        .HasColumnType("datetime2");

                    b.HasKey("ThanhToanId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_KhachHang.KhachHang", b =>
                {
                    b.Property<int>("KhachHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhachHangId"));

                    b.Property<string>("CCCD_Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiKhachHangId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuocTich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KhachHangId");

                    b.HasIndex("LoaiKhachHangId");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_KhachHang.LoaiKhachHang", b =>
                {
                    b.Property<int>("LoaiKhachHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiKhachHangId"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TyLeUuDai")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LoaiKhachHangId");

                    b.ToTable("LoaiKhachHangs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_NhanVien.ChucVu", b =>
                {
                    b.Property<int>("ChucVuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChucVuId"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChucVuId");

                    b.ToTable("ChucVus");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_NhanVien.NhanVien", b =>
                {
                    b.Property<int>("NhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienId"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChucVuId")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LuongCoBan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThaiLamViec")
                        .HasColumnType("int");

                    b.HasKey("NhanVienId");

                    b.HasIndex("ChucVuId");

                    b.HasIndex("MaNhanVien")
                        .IsUnique();

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.LoaiPhong", b =>
                {
                    b.Property<int>("LoaiPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiPhongId"));

                    b.Property<double>("DienTich")
                        .HasColumnType("float");

                    b.Property<decimal>("GiaCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoaiPhongId");

                    b.ToTable("LoaiPhongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.Phong", b =>
                {
                    b.Property<int>("PhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhongId"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiPhongId")
                        .HasColumnType("int");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TangId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("PhongId");

                    b.HasIndex("LoaiPhongId");

                    b.HasIndex("SoPhong")
                        .IsUnique();

                    b.HasIndex("TangId");

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.Tang", b =>
                {
                    b.Property<int>("TangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TangId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SoTang")
                        .HasColumnType("int");

                    b.HasKey("TangId");

                    b.ToTable("Tangs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_TaiKhoan.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanId"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.HasKey("TaiKhoanId");

                    b.HasIndex("NhanVienId")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.HasIndex("VaiTroId");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_TaiKhoan.VaiTro", b =>
                {
                    b.Property<int>("VaiTroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaiTroId"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaiTroId");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.ChiTietDatPhong", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_DatNhanTraPhong.DatPhong", "DatPhong")
                        .WithMany("ChiTietDatPhongs")
                        .HasForeignKey("DatPhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLKS.Data.Entities.Nhom_Phong.Phong", "Phong")
                        .WithMany("ChiTietDatPhongs")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatPhong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.ChiTietNhanPhong", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_DatNhanTraPhong.ChiTietDatPhong", "ChiTietDatPhong")
                        .WithMany("ChiTietNhanPhongs")
                        .HasForeignKey("ChiTietDatPhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLKS.Data.Entities.Nhom_DatNhanTraPhong.NhanPhong", "NhanPhong")
                        .WithMany("ChiTietNhanPhongs")
                        .HasForeignKey("NhanPhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiTietDatPhong");

                    b.Navigation("NhanPhong");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.ChiTietTraPhong", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_DatNhanTraPhong.ChiTietNhanPhong", "ChiTietNhanPhong")
                        .WithMany("ChiTietTraPhongs")
                        .HasForeignKey("ChiTietNhanPhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLKS.Data.Entities.Nhom_DatNhanTraPhong.TraPhong", "TraPhong")
                        .WithMany("ChiTietTraPhongs")
                        .HasForeignKey("TraPhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiTietNhanPhong");

                    b.Navigation("TraPhong");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.DatPhong", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_KhachHang.KhachHang", "KhachHang")
                        .WithMany("DatPhongs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.NhanPhong", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_NhanVien.NhanVien", "NhanVien")
                        .WithMany("NhanPhongs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.TraPhong", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_NhanVien.NhanVien", "NhanVien")
                        .WithMany("TraPhongs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DichVu.SuDungDichVu", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_DatNhanTraPhong.ChiTietDatPhong", "ChiTietDatPhong")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("ChiTietDatPhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLKS.Data.Entities.Nhom_DichVu.DichVu", "DichVu")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiTietDatPhong");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_HoaDon_ThanhToan.ChiTietHoaDon", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_DatNhanTraPhong.ChiTietDatPhong", "ChiTietDatPhong")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("ChiTietDatPhongId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QLKS.Data.Entities.Nhom_HoaDon_ThanhToan.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLKS.Data.Entities.Nhom_DichVu.SuDungDichVu", "SuDungDichVu")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("SuDungDichVuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChiTietDatPhong");

                    b.Navigation("HoaDon");

                    b.Navigation("SuDungDichVu");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_HoaDon_ThanhToan.HoaDon", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_DatNhanTraPhong.DatPhong", "DatPhong")
                        .WithMany("HoaDons")
                        .HasForeignKey("DatPhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLKS.Data.Entities.Nhom_KhachHang.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLKS.Data.Entities.Nhom_NhanVien.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatPhong");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_HoaDon_ThanhToan.ThanhToan", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_HoaDon_ThanhToan.HoaDon", "HoaDon")
                        .WithMany("ThanhToans")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_KhachHang.KhachHang", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_KhachHang.LoaiKhachHang", "LoaiKhachHang")
                        .WithMany("KhachHangs")
                        .HasForeignKey("LoaiKhachHangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiKhachHang");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_NhanVien.NhanVien", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_NhanVien.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("ChucVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.Phong", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_Phong.LoaiPhong", "LoaiPhong")
                        .WithMany("Phongs")
                        .HasForeignKey("LoaiPhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLKS.Data.Entities.Nhom_Phong.Tang", "Tang")
                        .WithMany("Phongs")
                        .HasForeignKey("TangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiPhong");

                    b.Navigation("Tang");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_TaiKhoan.TaiKhoan", b =>
                {
                    b.HasOne("QLKS.Data.Entities.Nhom_NhanVien.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("QLKS.Data.Entities.Nhom_TaiKhoan.TaiKhoan", "NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLKS.Data.Entities.Nhom_TaiKhoan.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.ChiTietDatPhong", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("ChiTietNhanPhongs");

                    b.Navigation("SuDungDichVus");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.ChiTietNhanPhong", b =>
                {
                    b.Navigation("ChiTietTraPhongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.DatPhong", b =>
                {
                    b.Navigation("ChiTietDatPhongs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.NhanPhong", b =>
                {
                    b.Navigation("ChiTietNhanPhongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DatNhanTraPhong.TraPhong", b =>
                {
                    b.Navigation("ChiTietTraPhongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DichVu.DichVu", b =>
                {
                    b.Navigation("SuDungDichVus");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_DichVu.SuDungDichVu", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_HoaDon_ThanhToan.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_KhachHang.KhachHang", b =>
                {
                    b.Navigation("DatPhongs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_KhachHang.LoaiKhachHang", b =>
                {
                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_NhanVien.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_NhanVien.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("NhanPhongs");

                    b.Navigation("TaiKhoan");

                    b.Navigation("TraPhongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.Phong", b =>
                {
                    b.Navigation("ChiTietDatPhongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_Phong.Tang", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("QLKS.Data.Entities.Nhom_TaiKhoan.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
